export { Authentication } from "./authentication/Authentication";
export { Login } from "./authentication/formComponents/Login";
export { Signup } from "./authentication/formComponents/Signup";
export { Home } from "./Home/Home";
export { Explore } from "./Explore/Explore";
export { Bookmarks } from "./Bookmarks/Bookmarks";
export { UserProfile } from "./UserProfile/UserProfile";
export { SinglePost } from "./SinglePost/SinglePost";
export { PageNotFound } from "./PageNotFound/PageNotFound";
