import {
  FaSmile,
  FaRegHeart,
  FaHeart,
  FaRegComments,
  FaRegBookmark,
  FaBookmark,
  FaFilter,
  FaFire,
  FaArrowUp,
  FaArrowDown,
  FaEdit,
  FaTrash,
  FaUserPlus,
  FaArrowLeft,
  FaTimes,
  FaCamera,
} from "react-icons/fa";
import {
  MdCancel,
  MdShare,
  MdHome,
  MdExplore,
  MdBookmarks,
  MdPerson,
  MdDateRange,
  MdOutlineLightMode,
  MdOutlineDarkMode,
  MdLogout,
} from "react-icons/md";
import { HiDotsHorizontal, HiPlusCircle, HiLink } from "react-icons/hi";
import { FiSearch } from "react-icons/fi";
import { AiOutlineEye, AiOutlineEyeInvisible } from "react-icons/ai";
import { RiUserUnfollowFill } from "react-icons/ri";
import { BsFillImageFill, BsPersonCircle } from "react-icons/bs";

export {
  FaSmile,
  FaRegHeart,
  FaHeart,
  FaRegComments,
  FaRegBookmark,
  FaBookmark,
  FaFilter,
  FaFire,
  FaArrowUp,
  FaArrowDown,
  FaEdit,
  FaTrash,
  FaUserPlus,
  FaArrowLeft,
  FaTimes,
  FaCamera,
  FiSearch,
  MdCancel,
  MdShare,
  MdHome,
  MdExplore,
  MdBookmarks,
  MdPerson,
  MdDateRange,
  MdOutlineLightMode,
  MdOutlineDarkMode,
  MdLogout,
  HiDotsHorizontal,
  HiPlusCircle,
  HiLink,
  AiOutlineEye,
  AiOutlineEyeInvisible,
  RiUserUnfollowFill,
  BsFillImageFill,
  BsPersonCircle,
};
